### ISSUE TITLE
no need to add imu in r3live

### ISSUE THREAD

**Issue by gongyue666** [engcang/SLAM-application#5]
Hi, in r3live demo, how do you add imu extrinsic to the whole project?

**Comment by engcang** [comment]
@gongyue666 Hi. Sorry for late reply. Looking into the official code of R3LiVE, they do not consider the IMU extrinsic but rather they seem to treat it as aligned with LiDAR, since they are officially providing the code with Livox AVIA model and the IMU extrinsic w.r.t. LiDAR of it is almost identity matrix.
